version: '3.3'

services:
  webapp:
    container_name: webapp
    image: murilloc/jms-pratica-1
    tty: true
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis
    networks:
      - webapp-network
    restart: always

  db:
    container_name: db
    image: mysql:5.7.30
    tty: true
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "33060:3306"
    volumes:
      - "./.docker/database:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: changeme!

    networks:
      - webapp-network


  redis:
    container_name: redis
    image: redis:6.0.3-alpine
    expose:
      - 6379
    networks:
      - webapp-network
    restart: always

  nginx:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - webapp
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
